### ISSUE TITLE
Consider replacing the aligned malloc calls with plain malloc

### ISSUE THREAD

**Issue by sunshowers** [jgehring/critbit89#2]
The aligned malloc calls ostensibly guarantee that the pointer returned is even, but that isn't necessary on any remotely modern architecture. malloc is guaranteed to return a value that is at least a multiple of sizeof(void*).

Would you consider a pull request replacing the aligned malloc calls with plain malloc? That'll also help you get rid of platform-specific ifdefs.

Cites:
http://pubs.opengroup.org/onlinepubs/009695399/functions/malloc.html
http://www.gnu.org/software/libc/manual/html_node/Aligned-Memory-Blocks.html

**Comment by jgehring** [comment]
Good point! The code uses sizeof(void *) alignments only, so this should work. Are you sure that MSVC's malloc will behave the same?

**Comment by sunshowers** [comment]
Yeah. The only architectures I'd be worried about are 8-bit ones. Another advantage of not using aligned malloc is that using it can apparently cause heap fragmentation.

Anyway, I'll put up a pull request soon.

**Comment by sunshowers** [comment]
See #4.
